version: "3.7"

services:
  frontend:
    build:
      context: ./frontend_trabalho2/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend_trabalho1/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_DB: "validatordb"
    ports:
      - "5432:5432"
    volumes:
      - validator-db:/var/lib/postgresql/data

volumes:
  validator-db:
